name: CI

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.0.0

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - run: 'npm run lint'

  Tests:
    needs: [Lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.0.0]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - run: npm run test:ci
        env:
          CI: true
